---
driver:
  name: vagrant
  customize:
    natdnshostresolver1: "on"
  network:
    - ["forwarded_port", {guest: 8000, host: 8000, auto_correct: true}]
    - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.11.18

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[jupyterhub-chef::default]
    attributes:
      dev_mode: true
